### ISSUE TITLE
WTForms-Alchemy issue with python 3.10

### ISSUE THREAD

**Issue by Te-k** [stopipv/isdi#39]
When running the last ISDI version on debian with python 3.10, I get : 

```
Traceback (most recent call last):
  File "/home/user/projects/stalkerware/isdi/./isdi", line 9, in <module>
    from web import app, sa
  File "/home/user/projects/stalkerware/isdi/web/__init__.py", line 22, in <module>
    import web.view
  File "/home/user/projects/stalkerware/isdi/web/view/__init__.py", line 2, in <module>
    from .consult import client_forms, edit_forms
  File "/home/user/projects/stalkerware/isdi/web/view/consult.py", line 4, in <module>
    from web.forms import ClientForm
  File "/home/user/projects/stalkerware/isdi/web/forms/__init__.py", line 1, in <module>
    from .client import ClientForm
  File "/home/user/projects/stalkerware/isdi/web/forms/client.py", line 1, in <module>
    from wtforms_alchemy import ModelForm
  File "/home/user/env/default3/lib/python3.10/site-packages/wtforms_alchemy/__init__.py", line 40, in <module>
    from .validators import Unique  # noqa
  File "/home/user/env/default3/lib/python3.10/site-packages/wtforms_alchemy/validators.py", line 1, in <module>
    from collections import Iterable, Mapping
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
``` 

Using the last version of [WTForms-Alchemy](https://pypi.org/project/WTForms-Alchemy/) (0.18.0) seems to solve this issue

**Comment by matreurai** [comment]
Stumbled upon the same issue, but updating WTForms-Alchemy did not work for me. Still unresolved on my end.

**Comment by rchatterjee** [comment]
Fixed this. Now ISDi should work with Python 3.10+
